name: cron

on:
  schedule:
    - cron: "49 10 * * *"
  pull_request:
    paths:
      - ".github/workflows/cron.yaml"
  workflow_call:
  workflow_dispatch: # allows manual triggering

jobs:
  update-rust-toolchain:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v3
      - uses: a-kenji/update-rust-toolchain@prepare-environment
        with:
          minor-version-delta: 1
          toolchain-path: "./rust-toolchain.toml"
          pr-title: "build: Update rust toolchain version"
